// goo.gl/gnpgmy
show dbs;
use Stadium;
db.createCollection("Clubs");
db.Clubs.insert({"Club":"Tottenham Hotspur FC","Stadium_Name":"Wembley National Stadium","Country":"England","City":"London","Capacity":90652})
db.Clubs.insert({"Club":"Manchester United FC","Stadium_Name":"Old Trafford","Country":"England","City":"Manchester","Capacity":74994})
db.Clubs.insert({"Club":"West Ham United FC","Stadium_Name":"London Stadium (Olympic Stadium)","Country":"England","City":"London","Capacity":60000})
db.Clubs.insert({"Club":"Arsenal FC","Stadium_Name":"Emirates Stadium (Ashburton Grove)","Country":"England","City":"London","Capacity":59867})
db.Clubs.insert({"Club":"Manchester City FC","Stadium_Name":"Etihad Stadium (City of Manchester Stadium / Eastlands)","Country":"England","City":"Manchester","Capacity":55017})
db.Clubs.insert({"Club":"Liverpool FC","Stadium_Name":"Anfield","Country":"England","City":"Liverpool","Capacity":53394})
db.Clubs.insert({"Club":"Newcastle United FC","Stadium_Name":"St. James’ Park","Country":"England","City":"Newcastle","Capacity":52354})
db.Clubs.insert({"Club":"Chelsea FC","Stadium_Name":"Stamford Bridge","Country":"England","City":"London","Capacity":41631})
db.Clubs.insert({"Club":"Everton FC","Stadium_Name":"Goodison Park","Country":"England","City":"Liverpool","Capacity":39595})
db.Clubs.insert({"Club":"Southampton FC","Stadium_Name":"St. Mary’s Stadium","Country":"England","City":"Southampton","Capacity":32384})
db.Clubs.insert({"Club":"Leicester City FC","Stadium_Name":"King Power Stadium (Filbert Way)","Country":"England","City":"Leicester","Capacity":32273})
db.Clubs.insert({"Club":"Brighton and Hove Albion","Stadium_Name":"American Express Community Stadium (Falmer Stadium)","Country":"England","City":"Brighton & Hove","Capacity":30666})
db.Clubs.insert({"Club":"Stoke City FC","Stadium_Name":"bet365 Stadium","Country":"England","City":"Stoke-on-Trent","Capacity":30089})
db.Clubs.insert({"Club":"West Bromwich Albion FC","Stadium_Name":"The Hawthorns","Country":"England","City":"West Bromwich","Capacity":26688})
db.Clubs.insert({"Club":"Crystal Palace FC","Stadium_Name":"Selhurst Park","Country":"England","City":"London","Capacity":25456})
db.Clubs.insert({"Club":"Huddersfield Town FC","Stadium_Name":"John Smith’s Stadium (Kirklees Stadium)","Country":"England","City":"Huddersfield","Capacity":24169})
db.Clubs.insert({"Club":"Burnley FC","Stadium_Name":"Turf Moor","Country":"England","City":"Burnley","Capacity":21944})
db.Clubs.insert({"Club":"Watford FC","Stadium_Name":"Vicarage Road","Country":"England","City":"Watford","Capacity":21000})
db.Clubs.insert({"Club":"AFC Bournemouth","Stadium_Name":"Vitality Stadium (Dean Court)","Country":"England","City":"Bournemouth","Capacity":11360})
db.Clubs.insert({"Club":"Sunderland AFC","Stadium_Name":"Stadium of Light","Country":"England","City":"Sunderland","Capacity":48707})
db.Clubs.insert({"Club":"Aston Villa FC","Stadium_Name":"Villa Park","Country":"England","City":"Birmingham","Capacity":42682})
db.Clubs.insert({"Club":"Sheffield Wednesday FC","Stadium_Name":"Hillsborough Stadium","Country":"England","City":"Sheffield","Capacity":39812})
db.Clubs.insert({"Club":"Leeds United FC","Stadium_Name":"Elland Road","Country":"England","City":"Leeds","Capacity":39460})
db.Clubs.insert({"Club":"Middlesbrough FC","Stadium_Name":"Riverside Stadium","Country":"England","City":"Middlesbrough","Capacity":33746})
db.Clubs.insert({"Club":"Derby County FC","Stadium_Name":"Pride Park Stadium","Country":"England","City":"Derby","Capacity":33597})
db.Clubs.insert({"Club":"Sheffield United FC","Stadium_Name":"Bramall Lane","Country":"England","City":"Sheffield","Capacity":32702})
db.Clubs.insert({"Club":"Wolverhampton Wanderers FC","Stadium_Name":"Molineux Stadium","Country":"England","City":"Wolverhampton","Capacity":32057})
db.Clubs.insert({"Club":"Nottingham Forest","Stadium_Name":"City Ground (Trentside)","Country":"England","City":"Nottingham","Capacity":30445})
db.Clubs.insert({"Club":"Ipswich Town","Stadium_Name":"Portman Road","Country":"England","City":"Ipswich","Capacity":30311})
db.Clubs.insert({"Club":"Birmingham City FC","Stadium_Name":"St. Andrew’s Stadium","Country":"England","City":"Birmingham","Capacity":30009})
db.Clubs.insert({"Club":"Bolton Wanderers FC","Stadium_Name":"Macron Stadium","Country":"England","City":"Bolton","Capacity":28723})
db.Clubs.insert({"Club":"Bristol City FC","Stadium_Name":"Ashton Gate","Country":"England","City":"Bristol","Capacity":27699})
db.Clubs.insert({"Club":"Norwich City FC","Stadium_Name":"Carrow Road","Country":"England","City":"Norwich","Capacity":27033})
db.Clubs.insert({"Club":"Fulham FC","Stadium_Name":"Craven Cottage","Country":"England","City":"London","Capacity":25700})
db.Clubs.insert({"Club":"Hull City AFC","Stadium_Name":"KCOM Stadium","Country":"England","City":"Hull","Capacity":24983})
db.Clubs.insert({"Club":"Reading FC","Stadium_Name":"Madejski Stadium","Country":"England","City":"Reading","Capacity":24161})
db.Clubs.insert({"Club":"Preston North End FC","Stadium_Name":"Deepdale Stadium","Country":"England","City":"Preston","Capacity":23404})
db.Clubs.insert({"Club":"Barnsley FC","Stadium_Name":"Oakwell Stadium","Country":"England","City":"Barnsley","Capacity":23009})
db.Clubs.insert({"Club":"Millwall FC","Stadium_Name":"The Den","Country":"England","City":"London","Capacity":20146})
db.Clubs.insert({"Club":"Queens Park Rangers","Stadium_Name":"Loftus Road","Country":"England","City":"London","Capacity":18000})
db.Clubs.insert({"Club":"Brentford FC","Stadium_Name":"Griffin Park","Country":"England","City":"London","Capacity":12300})
db.Clubs.insert({"Club":"Burton Albion FC","Stadium_Name":"Pirelli Stadium","Country":"England","City":"Burton upon Trent","Capacity":6912})
db.Clubs.insert({"Club":"Blackburn Rovers FC","Stadium_Name":"Ewood Park","Country":"England","City":"Blackburn","Capacity":31154})
db.Clubs.insert({"Club":"Milton Keynes Dons FC","Stadium_Name":"Stadium mk (Denbigh Stadium)","Country":"England","City":"Milton Keynes","Capacity":30700})
db.Clubs.insert({"Club":"Charlton Athletic FC","Stadium_Name":"The Valley","Country":"England","City":"London","Capacity":27111})
db.Clubs.insert({"Club":"Wigan Athletic","Stadium_Name":"DW Stadium","Country":"England","City":"Wigan","Capacity":25138})
db.Clubs.insert({"Club":"Bradford City FC","Stadium_Name":"Valley Parade Stadium","Country":"England","City":"Bradford","Capacity":25100})
db.Clubs.insert({"Club":"Portsmouth FC","Stadium_Name":"Fratton Park","Country":"England","City":"Portsmouth","Capacity":20821})
db.Clubs.insert({"Club":"Notts County","Stadium_Name":"Meadow Lane","Country":"England","City":"Nottingham","Capacity":20229})
db.Clubs.insert({"Club":"Plymouth Argyle FC","Stadium_Name":"Home Park","Country":"England","City":"Plymouth","Capacity":16388})
db.Clubs.insert({"Club":"Blackpool FC","Stadium_Name":"Bloomfield Road","Country":"England","City":"Blackpool","Capacity":16220})
db.Clubs.insert({"Club":"Doncaster Rovers FC","Stadium_Name":"Keepmoat Stadium (Lakeside Spors Complex)","Country":"England","City":"Doncaster","Capacity":15231})
db.Clubs.insert({"Club":"Peterborough United","Stadium_Name":"ABAX Stadium (London Road)","Country":"England","City":"Peterborough","Capacity":14319})
db.Clubs.insert({"Club":"Oxford United FC","Stadium_Name":"Kassam Stadium","Country":"England","City":"Oxford","Capacity":12500})
db.Clubs.insert({"Club":"Southend United FC","Stadium_Name":"Roots Hall","Country":"England","City":"Southend-on-Sea","Capacity":12392})
db.Clubs.insert({"Club":"Rotherham United FC","Stadium_Name":"New York AESSEAL Stadium","Country":"England","City":"Rotherham","Capacity":12021})
db.Clubs.insert({"Club":"Bury FC","Stadium_Name":"Gigg Lane","Country":"England","City":"Bury","Capacity":11840})
db.Clubs.insert({"Club":"Gillingham FC","Stadium_Name":"MEMS Priestfield Stadium","Country":"England","City":"Gillingham","Capacity":11582})
db.Clubs.insert({"Club":"Walsall FC","Stadium_Name":"Banks’s Stadium (Bescot Stadium)","Country":"England","City":"Walsall","Capacity":11300})
db.Clubs.insert({"Club":"Oldham Athletic AFC","Stadium_Name":"Boundary Park","Country":"England","City":"Oldham","Capacity":10638})
db.Clubs.insert({"Club":"Rochdale AFC","Stadium_Name":"Spotland Stadium","Country":"England","City":"Rochdale","Capacity":10249})
db.Clubs.insert({"Club":"Shrewsbury Town FC","Stadium_Name":"Montgomery Waters Meadow Stadium (New Meadow, Oteley Road)","Country":"England","City":"Shrewsbury","Capacity":9875})
db.Clubs.insert({"Club":"Yeovil Town FC","Stadium_Name":"Huish Park Stadium","Country":"England","City":"Yeovil","Capacity":9665})
db.Clubs.insert({"Club":"Leyton Orient FC","Stadium_Name":"Matchroom Stadium (Brisbane Road)","Country":"England","City":"London","Capacity":9271})
db.Clubs.insert({"Club":"Scunthorpe United FC","Stadium_Name":"Glanford Park","Country":"England","City":"Scunthorpe","Capacity":9088})
db.Clubs.insert({"Club":"Fleetwood Town FC","Stadium_Name":"Highbury Stadium","Country":"England","City":"Fleetwood","Capacity":5094})
db.Clubs.insert({"Club":"West Ham United FC","Stadium_Name":"Boleyn Ground (Upton Park)","Country":"England","City":"London","Capacity":35345})
db.Clubs.insert({"Club":"Coventry City FC","Stadium_Name":"Ricoh Arena","Country":"England","City":"Coventry","Capacity":32609})
db.Clubs.insert({"Club":"Tottenham Hotspur FC","Stadium_Name":"White Hart Lane","Country":"England","City":"London","Capacity":32000})
db.Clubs.insert({"Club":"Port Vale FC","Stadium_Name":"Vale Park","Country":"England","City":"Stoke-on-Trent","Capacity":19052})
db.Clubs.insert({"Club":"St. Helens RFC","Stadium_Name":"Totally Wicked Stadium (St Helens Stadium)","Country":"England","City":"St Helens","Capacity":17646})
db.Clubs.insert({"Club":"Carlisle United FC","Stadium_Name":"Brunton Park","Country":"England","City":"Carlisle","Capacity":16980})
db.Clubs.insert({"Club":"Tranmere Rovers FC","Stadium_Name":"Prenton Park","Country":"England","City":"Birkenhead","Capacity":16587})
db.Clubs.insert({"Club":"Swindon Town FC","Stadium_Name":"County Ground","Country":"England","City":"Swindon","Capacity":15728})
db.Clubs.insert({"Club":"Bristol Rovers FC","Stadium_Name":"Bristol Memorial Stadium","Country":"England","City":"Bristol","Capacity":11917})
db.Clubs.insert({"Club":"Chesterfield FC","Stadium_Name":"Proact Stadium","Country":"England","City":"Chesterfield","Capacity":10379})
db.Clubs.insert({"Club":"Wycombe Wanderers FC","Stadium_Name":"Adams Park","Country":"England","City":"Wycombe","Capacity":10284})
db.Clubs.insert({"Club":"Luton Town FC","Stadium_Name":"Kenilworth Road Stadium","Country":"England","City":"Luton","Capacity":10226})
db.Clubs.insert({"Club":"Crewe Alexandra FC","Stadium_Name":"Alexandra Stadium (Gresty Road)","Country":"England","City":"Crewe","Capacity":10153})
db.Clubs.insert({"Club":"Lincoln  City FC","Stadium_Name":"Sincil Bank Stadium (The Bank)","Country":"England","City":"Lincoln","Capacity":10127})
db.Clubs.insert({"Club":"Colchester United FC","Stadium_Name":"Weston Homes Community Stadium (Colchester Community Stadium)","Country":"England","City":"Colchester","Capacity":10084})
db.Clubs.insert({"Club":"Cambridge United FC","Stadium_Name":"Abbey Stadium","Country":"England","City":"Cambridge","Capacity":9617})
db.Clubs.insert({"Club":"Mansfield Town FC","Stadium_Name":"One Call Stadium (Field Mill)","Country":"England","City":"Mansfield","Capacity":9186})
db.Clubs.insert({"Club":"Grimsby Town FC","Stadium_Name":"Blundell Park","Country":"England","City":"Grimsby","Capacity":9052})
db.Clubs.insert({"Club":"Exeter City FC","Stadium_Name":"St James Park, Exeter","Country":"England","City":"Exeter","Capacity":8541})
db.Clubs.insert({"Club":"Hartlepool United FC","Stadium_Name":"Victoria Park","Country":"England","City":"Hartlepool","Capacity":7856})
db.Clubs.insert({"Club":"Northampton Town FC","Stadium_Name":"Sixfields Stadium","Country":"England","City":"Northampton","Capacity":7653})
db.Clubs.insert({"Club":"Grantham Town FC","Stadium_Name":"South Kesteven Sports Stadium (The Meres)","Country":"England","City":"Grantham","Capacity":7500})
db.Clubs.insert({"Club":"Chaltenham Town FC, Gloucester City AFC","Stadium_Name":"Abbey Business Stadium (Whaddon Road)","Country":"England","City":"Chaltenham","Capacity":7066})
db.Clubs.insert({"Club":"Manchester City FC","Stadium_Name":"Manchester City Football Academy Stadium","Country":"England","City":"Manchester","Capacity":7000})
db.Clubs.insert({"Club":"Torquay United FC","Stadium_Name":"Plainmoor","Country":"England","City":"Torquay","Capacity":6500})
db.Clubs.insert({"Club":"Morecambe FC","Stadium_Name":"Globe Arena","Country":"England","City":"Morecambe","Capacity":6476})
db.Clubs.insert({"Club":"Macclesfield Town FC","Stadium_Name":"Moss Rose","Country":"England","City":"Macclesfield","Capacity":6355})
db.Clubs.insert({"Club":"Kidderminster Harriers FC","Stadium_Name":"Aggborough","Country":"England","City":"Kidderminster","Capacity":6238})
db.Clubs.insert({"Club":"Barnet FC","Stadium_Name":"The Hive Stadium","Country":"England","City":"London","Capacity":6205})
db.Clubs.insert({"Club":"Crawley Town FC","Stadium_Name":"Checkatrade.com Stadium (Broadfield Stadium)","Country":"England","City":"Crawley","Capacity":6134})
db.Clubs.insert({"Club":"Dagenham & Redbridge FC","Stadium_Name":"Victoria Road (London Borough of Barking & Dagenham Stadium)","Country":"England","City":"London","Capacity":6078})
db.Clubs.insert({"Club":"Southport FC","Stadium_Name":"Merseyrail Community Stadium (Haig Avenue)","Country":"England","City":"Southport","Capacity":6008})
db.Clubs.insert({"Club":"AFC Fylde","Stadium_Name":"Mill Farm","Country":"England","City":"Medlar with Wesham","Capacity":6000})
db.Clubs.insert({"Club":"Chester FC","Stadium_Name":"Lookers Vauxhall Stadium","Country":"England","City":"Chester","Capacity":5376})
db.Clubs.insert({"Club":"Accrington Stanley FC","Stadium_Name":"Wham Stadium","Country":"England","City":"Accrington","Capacity":5057})
db.Clubs.insert({"Club":"Forest Green Rovers FC","Stadium_Name":"The New Lawn","Country":"England","City":"Nailsworth","Capacity":5032})
db.Clubs.insert({"Club":"Ebbsfleet United FC","Stadium_Name":"PHB Stadium (Stonebridge Road)","Country":"England","City":"Northfleet","Capacity":5011})
db.Clubs.insert({"Club":"Kingstonian FC, AFC Wimbledon","Stadium_Name":"The Cherry Red Records Stadium (Kingsmeadow)","Country":"England","City":"London","Capacity":4850})
db.Clubs.insert({"Club":"FC United of Manchester","Stadium_Name":"Broadhurst Park","Country":"England","City":"Manchester","Capacity":4400})
db.Clubs.insert({"Club":"Dartford FC","Stadium_Name":"Princes Park Stadium (Dartford)","Country":"England","City":"Dartford","Capacity":4100})
db.Clubs.insert({"Club":"Hyde FC","Stadium_Name":"Ewen Fields","Country":"England","City":"Hyde","Capacity":4073})
db.Clubs.insert({"Club":"Curzon Ashton FC","Stadium_Name":"Tameside Stadium","Country":"England","City":"Ashton-under-Lyne","Capacity":4000})
db.Clubs.insert({"Club":"Salford City FC","Stadium_Name":"Moor Lane","Country":"England","City":"Salford","Capacity":3339})
db.Clubs.insert({"Club":"Lewes FC","Stadium_Name":"The Dripping Pan","Country":"England","City":"Lewes","Capacity":3000})
db.Clubs.insert({"Club":"Matlock Town FC","Stadium_Name":"DCJ Group Insurance Arena (Causeway Lane)","Country":"England","City":"Matlock","Capacity":2757})
db.Clubs.insert({"Club":"Hallam FC","Stadium_Name":"Sandygate Road","Country":"England","City":"Sheffield","Capacity":700})
db.Clubs.insert({"Club":"Arsenal FC","Stadium_Name":"Arsenal Stadium (Highbury) – until 2006","Country":"England","City":"London","Capacity":38500})
db.Clubs.insert({"Club":"Manchester City FC","Stadium_Name":"Maine Road – until 2003","Country":"England","City":"Manchester","Capacity":35150})
db.Clubs.insert({"Club":"Stoke City FC","Stadium_Name":"Victoria Ground – until 1997","Country":"England","City":"Stoke-on-Trent","Capacity":22500})
db.Clubs.insert({"Club":"Manchester City","Stadium_Name":"Etihad Stadium","Country":"England","City":"Manchester","Capacity":62170})
db.Clubs.insert({"Club":"Tottenham","Stadium_Name":"New Tottenham Stadium","Country":"England","City":"London","Capacity":61559})
db.Clubs.insert({"Club":"Liverpool FC","Stadium_Name":"Anfield","Country":"England","City":"Liverpool","Capacity":58800})
db.Clubs.insert({"Club":"Wanderers","Stadium_Name":"Molineux Stadium","Country":"England","City":"Wolverhampton","Capacity":37500})
db.Clubs.insert({"Club":"Brentford FC","Stadium_Name":"Brentford Community Stadium","Country":"England","City":"London","Capacity":17250})
db.Clubs.insert({"Club":"Oldham Athletic","Stadium_Name":"Boundary Park","Country":"England","City":"Oldham","Capacity":13000})
db.Clubs.insert({"Club":"York City, Knights","Stadium_Name":"York Community Stadium","Country":"England","City":"York","Capacity":8113})
db.Clubs.insert({"Club":"Ebbsfleet United","Stadium_Name":"PHB Stadium","Country":"England","City":"Northfleet","Capacity":6000})
db.Clubs.insert({"Club":"Salford City","Stadium_Name":"Moor Lane","Country":"England","City":"Salford","Capacity":5108})
db.Clubs.insert({"Club":"Chelsea FC","Stadium_Name":"Stamford Bridge","Country":"England","City":"London","Capacity":60000})
db.Clubs.insert({"Club":"Sheffield United","Stadium_Name":"Bramall Lane","Country":"England","City":"Sheffield","Capacity":41300})
db.Clubs.insert({"Club":"Crystal Palace","Stadium_Name":"Selhurst Park","Country":"England","City":"London","Capacity":34000})
db.Clubs.insert({"Club":"Fulham FC","Stadium_Name":"Craven Cottage","Country":"England","City":"London","Capacity":29600})
db.Clubs.insert({"Club":"Southend United","Stadium_Name":"Fossetts Farm Stadium","Country":"England","City":"Southend-on-Sea","Capacity":21001})
db.Clubs.insert({"Club":"Wimbledon","Stadium_Name":"Plough Lane","Country":"England","City":"London","Capacity":2000})
db.Clubs.insert({"Club":"Luton Town","Stadium_Name":"Power Court Stadium","Country":"England","City":"Luton","Capacity":17500})
db.Clubs.insert({"Club":"Grimsby Town","Stadium_Name":"Grimsby Community Stadium","Country":"England","City":"Grimsby","Capacity":14000})
db.Clubs.insert({"Club":"Cambridge United","Stadium_Name":"Abbey Stadium","Country":"England","City":"Cambridge","Capacity":11000})
db.Clubs.insert({"Club":"Forest Green Rovers","Stadium_Name":"Eco Park (I)","Country":"England","City":"Stonehouse","Capacity":10000})
db.Clubs.insert({"Club":"Leamington FC","Stadium_Name":"Leamington Community Stadium","Country":"England","City":"Leamington Spa","Capacity":5000})
db.Clubs.insert({"Club":"Stanley","Stadium_Name":"Wham Stadium","Country":"England","City":"Accrington","Capacity":5000})
db.Clubs.insert({"Club":"Boston United","Stadium_Name":"Boston Community Stadium","Country":"England","City":"Boston","Capacity":42329})
db.Clubs.insert({"Club":"Cambridge City","Stadium_Name":"Sawston Ground","Country":"England","City":"Sawston","Capacity":3000})
db.Clubs.insert({"Club":"Arsenal Londyn","Stadium_Name":"Emirates Stadium","Country":"England","City":"London","Capacity":60000})
db.Clubs.insert({"Club":"West Ham United","Stadium_Name":"London Olympic Stadium","Country":"England","City":"London","Capacity":60000})
db.Clubs.insert({"Club":"Coventry City FC","Stadium_Name":"Ricoh Arena","Country":"England","City":"Coventry","Capacity":32000})
db.Clubs.insert({"Club":"Bristol City","Stadium_Name":"Ashton Gate","Country":"England","City":"Bristol","Capacity":27000})
db.Clubs.insert({"Club":"Brighton & Hove Albion FC","Stadium_Name":"American Express Community Stadium","Country":"England","City":"Brighton & Hove","Capacity":22347})
db.Clubs.insert({"Club":"Rotherham United","Stadium_Name":"Rotherham United Stadium","Country":"England","City":"Rotherham","Capacity":12000})
db.Clubs.insert({"Club":"Manchester City","Stadium_Name":"City Football Academy Arena","Country":"England","City":"Manchester","Capacity":7000})
db.Clubs.insert({"Club":"FC United, Moston Juniors","Stadium_Name":"Broadhurst Park","Country":"England","City":"Manchester","Capacity":5000})
db.Clubs.insert({"Club":"Liverpool FC","Stadium_Name":"Stanley Park (New Anfield)","Country":"England","City":"Liverpool","Capacity":73000})
db.Clubs.insert({"Club":"Chelsea FC","Stadium_Name":"Chelsea Battersea Stadium","Country":"England","City":"London","Capacity":60000})
db.Clubs.insert({"Club":"Liverpool FC","Stadium_Name":"Stanley Park (New Anfield)","Country":"England","City":"Liverpool","Capacity":60000})
db.Clubs.insert({"Club":"Tottenham","Stadium_Name":"New Tottenham Stadium","Country":"England","City":"London","Capacity":56250})
db.Clubs.insert({"Club":"Everton","Stadium_Name":"King’s Dock Stadium","Country":"England","City":"Liverpool","Capacity":55000})
db.Clubs.insert({"Club":"Newcastle United","Stadium_Name":"Leazes Park Stadium","Country":"England","City":"Newcastle","Capacity":55000})
db.Clubs.insert({"Club":"Everton FC","Stadium_Name":"Kirkby Stadium","Country":"England","City":"Kirkby","Capacity":50401})
db.Clubs.insert({"Club":"Southampton FC","Stadium_Name":"St. Mary’s Stadium","Country":"England","City":"Southampton","Capacity":50000})
db.Clubs.insert({"Club":"Everton","Stadium_Name":"Walton Hall Park Stadium (I)","Country":"England","City":"Liverpool","Capacity":50000})
db.Clubs.insert({"Club":"Everton","Stadium_Name":"Walton Hall Park Stadium (II)","Country":"England","City":"Liverpool","Capacity":50000})
db.Clubs.insert({"Club":"QPR","Stadium_Name":"New Queens Park","Country":"England","City":"London","Capacity":40000})
db.Clubs.insert({"Club":"Portsmouth FC","Stadium_Name":"Portsmouth Dockland Stadium","Country":"England","City":"Portsmouth","Capacity":36000})
db.Clubs.insert({"Club":"Bristol City","Stadium_Name":"Bristol City Stadium","Country":"England","City":"Bristol","Capacity":30000})
db.Clubs.insert({"Club":"Fulham FC","Stadium_Name":"Craven Cottage","Country":"England","City":"London","Capacity":30000})
db.Clubs.insert({"Club":"Coventry City","Stadium_Name":"Coventry City Stadium","Country":"England","City":"Coventry","Capacity":23000})
db.Clubs.insert({"Club":"Bristol Rovers","Stadium_Name":"UWE Stadium","Country":"England","City":"Bristol","Capacity":21700})
db.Clubs.insert({"Club":"Rovers","Stadium_Name":"New Memorial Stadium","Country":"England","City":"Bristol","Capacity":18500})
db.Clubs.insert({"Club":"Oldham Athletic","Stadium_Name":"Oldham Arena","Country":"England","City":"Oldham","Capacity":16000})
db.Clubs.insert({"Club":"Scunthorpe United","Stadium_Name":"Scunthorpe United Stadium","Country":"England","City":"Scunthorpe","Capacity":12000})
db.Clubs.insert({"Club":"Forest Green Rovers","Stadium_Name":"Eco Park (II)","Country":"England","City":"Stonehouse","Capacity":10000})
db.Clubs.insert({"Club":"Forest Green Rovers","Stadium_Name":"Eco Park (III)","Country":"England","City":"Stonehouse","Capacity":10000})
db.Clubs.insert({"Club":"Fulham FC","Stadium_Name":"Craven Cottage (I)","Country":"England","City":"London","Capacity":39000})
db.Clubs.insert({"Club":"Tottenham Hotspur","Stadium_Name":"New Tottenham Stadium","Country":"England","City":"London","Capacity":12345})
db.Clubs.insert({"Club":"Salford City","Stadium_Name":"Moor Lane","Country":"England","City":"Salford","Capacity":24564})
db.Clubs.insert({"Club":"Liverpool FC","Stadium_Name":"Anfield","Country":"England","City":"Liverpool","Capacity":30978})
db.Clubs.insert({"Club":"Bristol City FC","Stadium_Name":"Ashton Gate","Country":"England","City":"Bristol","Capacity":12312})
db.Clubs.insert({"Club":"Manchester City FC","Stadium_Name":"Etihad Stadium (City of Manchester Stadium / Eastlands)","Country":"England","City":"Manchester","Capacity":32412})
db.Clubs.insert({"Club":"FC United of Manchester","Stadium_Name":"Broadhurst Park (Moston Community Stadium)","Country":"England","City":"Manchester","Capacity":4567})
db.Clubs.insert({"Club":"Manchester City FC","Stadium_Name":"City Football Academy Arena","Country":"England","City":"Manchester","Capacity":12312})
db.Clubs.insert({"Club":"Wolverhampton Wanderers","Stadium_Name":"Molineux แ","Country":"England","City":"Wolverhampton","Capacity":11111})
db.Clubs.insert({"Club":"Brighton & Hove Albion FC","Stadium_Name":"American Express Community Stadium (Falmer Stadium)","Country":"England","City":"Brighton & Hove","Capacity":23212})
db.Clubs.insert({"Club":"Morecambe FC","Stadium_Name":"Globe Arena (Morecambe FC New Stadium)","Country":"England","City":"Morecambe","Capacity":5652})

//1. แสดงข้อมูลสนามทั้งหมดเรียงตามชื่อเมือง
db.Clubs.find({}).sort({"City":1})

//2. แสดงข้อมูลสนามในเมือง Liverpool
db.Clubs.find({"City":"Liverpool"})

//3. แสดงข้อมูลสนาม ที่ชื่อสนามลงท้ายด้วย Stadium
db.Clubs.find({"Stadium_Name":{"$regex":"Stadium$"}})

//4. แสดงข้อมูลสนาม ที่ชื่อสโมสรมีคำว่า FC อยู่ด้วย
db.Clubs.find({"Club":{"$regex":"FC","$options":"i"}})

//5. แสดงข้อมูลสนามที่มีความจุมากกว่า 20000
db.Clubs.find({"Capacity":{"$gt":20000}})

//6. แสดงข้อมูลสนามที่มีความจุตั้งแต่ 20000 - 40000 โดยเรียงตามความจุมากที่สุดมาก่อน
db.Clubs.find({"$and":[{"Capacity":{"$gte":20000}},{"Capacity":{"$lte":40000}}]}).sort({"Capacity":-1})

//7. แสดงข้อมูลสนามใน London ที่มีความจุน้อยกว่า 20000
db.Clubs.find({"$and":[{"City":"London"},{"Capacity":{"$lt":20000}}]})

//8. เรียงข้อมูลโดยให้สนามที่มีความจุมากที่สุดแสดงขึ้นมาก่อน โดยถ้ามีความจุเท่ากันให้เรียงตามชื่อสโมสร
db.Clubs.find({}).sort({"Capacity":-1,"Club":1})

//9. แสดงข้อมูลสนามในเมือง Bristol , London , Luton ที่มีความจุมากกว่า 15000 ที่นั่ง
db.Clubs.find({"$and":[{"City":{"$in":["Bristol","London","Luton"]}},{"Capacity":{"$gt":15000}}]})

//10. แสดงข้อมูลสนามที่มีความจุต่ำกว่า 10000 หรือ มีคำว่า FC ในชื่อสนาม โดยให้เรียงตามชื่อเมือง
db.Clubs.find({"$or":[{"Capacity":{"$lt":10000}},{"Stadium_Name":{"$regex":"FC"}}]}).sort({"City":1})
