# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pymongo
from datetime import datetime
from PyQt5 import QtCore, QtGui, QtWidgets

import Register

cloudDatabase = "mongodb+srv://test:<password>@cluster0.hf3dm.mongodb.net/QT?retryWrites=true&w=majority"


class Ui_frm_login(object):
    def setupUi(self, frm_login):
        frm_login.setObjectName("frm_login")
        frm_login.resize(500, 300)
        self.lbl_Username = QtWidgets.QLabel(frm_login)
        self.lbl_Username.setGeometry(QtCore.QRect(80, 80, 81, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.lbl_Username.setFont(font)
        self.lbl_Username.setObjectName("lbl_Username")
        self.lbl_Password = QtWidgets.QLabel(frm_login)
        self.lbl_Password.setGeometry(QtCore.QRect(80, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.lbl_Password.setFont(font)
        self.lbl_Password.setObjectName("lbl_Password")
        self.txt_username = QtWidgets.QLineEdit(frm_login)
        self.txt_username.setGeometry(QtCore.QRect(180, 80, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_username.setFont(font)
        self.txt_username.setObjectName("txt_username")
        self.txt_password = QtWidgets.QLineEdit(frm_login)
        self.txt_password.setGeometry(QtCore.QRect(180, 130, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_password.setFont(font)
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setObjectName("txt_password")
        self.btn_Login = QtWidgets.QPushButton(frm_login)
        self.btn_Login.setGeometry(QtCore.QRect(150, 220, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_Login.setFont(font)
        self.btn_Login.setObjectName("btn_Login")
        self.btn_Register = QtWidgets.QPushButton(frm_login)
        self.btn_Register.setGeometry(QtCore.QRect(30, 220, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_Register.setFont(font)
        self.btn_Register.setObjectName("btn_Register")
        self.lbl_Result = QtWidgets.QLabel(frm_login)
        self.lbl_Result.setGeometry(QtCore.QRect(300, 220, 180, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_Result.setFont(font)
        self.lbl_Result.setText("")
        self.lbl_Result.setObjectName("lbl_Result")

        self.retranslateUi(frm_login)
        QtCore.QMetaObject.connectSlotsByName(frm_login)

        # Event-Driven
        self.btn_Login.clicked.connect(self.login)
        self.btn_Register.clicked.connect(self.register)

    def login(self):
        try:
            username = self.txt_username.text()
            password = self.txt_password.text()
            with pymongo.MongoClient(cloudDatabase) as conn:
                db = conn.get_database('QT')
                con1 = {'username': {"$regex": f'^{username}$', "$options": "i"}}
                con2 = {'password': password}
                where = {'$and': [con1, con2]}
                found = db.users.count_documents(where)
                if found:
                    cursor = db.users.find(where)
                    name = cursor[0]['name']
                    self.lbl_Result.setText(name)
                    setTo = {'$set': {'last_access': datetime.now()}}
                    db.users.update_one(where, setTo)
                else:
                    self.lbl_Result.setText("ไม่พบชื่อผู้ใช้หรือรหัสผ่านผิด")
        except Exception as e:
            print(e)

    def register(self):
        frm_login.hide()
        frm_Register.exec_()
        frm_login.show()

    def retranslateUi(self, frm_login):
        _translate = QtCore.QCoreApplication.translate
        frm_login.setWindowTitle(_translate("frm_login", "Login"))
        self.lbl_Username.setText(_translate("frm_login", "Username"))
        self.lbl_Password.setText(_translate("frm_login", "Password"))
        self.btn_Register.setText(_translate("frm_login", "New Register"))
        self.btn_Login.setText(_translate("frm_login", "Login"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    frm_login = QtWidgets.QDialog()
    ui = Ui_frm_login()
    ui.setupUi(frm_login)
    frm_login.show()

    frm_Register = QtWidgets.QDialog()
    ui_Register = Register.Ui_frm_Register()
    ui_Register.setupUi(frm_Register)

    sys.exit(app.exec_())
