# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pymongo
from datetime import datetime
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

# from Login import cloudDatabase
cloudDatabase = "mongodb+srv://test:<password>@cluster0.hf3dm.mongodb.net/QT?retryWrites=true&w=majority"


class Ui_frm_Register(object):
    def setupUi(self, frm_Register):
        frm_Register.setObjectName("frm_Register")
        frm_Register.resize(500, 350)
        self.lbl_Result = QtWidgets.QLabel(frm_Register)
        self.lbl_Result.setGeometry(QtCore.QRect(200, 270, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_Result.setFont(font)
        self.lbl_Result.setText("")
        self.lbl_Result.setObjectName("lbl_Result")
        self.txt_username = QtWidgets.QLineEdit(frm_Register)
        self.txt_username.setGeometry(QtCore.QRect(200, 60, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_username.setFont(font)
        self.txt_username.setObjectName("txt_username")
        self.lbl_Username = QtWidgets.QLabel(frm_Register)
        self.lbl_Username.setGeometry(QtCore.QRect(70, 60, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.lbl_Username.setFont(font)
        self.lbl_Username.setObjectName("lbl_Username")
        self.lbl_Name = QtWidgets.QLabel(frm_Register)
        self.lbl_Name.setGeometry(QtCore.QRect(70, 100, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.lbl_Name.setFont(font)
        self.lbl_Name.setObjectName("lbl_Name")
        self.txt_Name = QtWidgets.QLineEdit(frm_Register)
        self.txt_Name.setGeometry(QtCore.QRect(200, 100, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_Name.setFont(font)
        self.txt_Name.setObjectName("txt_Name")
        self.txt_password = QtWidgets.QLineEdit(frm_Register)
        self.txt_password.setGeometry(QtCore.QRect(200, 150, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_password.setFont(font)
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setObjectName("txt_password")
        self.lbl_Password = QtWidgets.QLabel(frm_Register)
        self.lbl_Password.setGeometry(QtCore.QRect(70, 150, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.lbl_Password.setFont(font)
        self.lbl_Password.setObjectName("lbl_Password")
        self.txt_RePassword = QtWidgets.QLineEdit(frm_Register)
        self.txt_RePassword.setGeometry(QtCore.QRect(200, 190, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_RePassword.setFont(font)
        self.txt_RePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_RePassword.setObjectName("txt_RePassword")
        self.lbl_RePassword = QtWidgets.QLabel(frm_Register)
        self.lbl_RePassword.setGeometry(QtCore.QRect(70, 190, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.lbl_RePassword.setFont(font)
        self.lbl_RePassword.setObjectName("lbl_RePassword")
        self.btn_Register = QtWidgets.QPushButton(frm_Register)
        self.btn_Register.setGeometry(QtCore.QRect(60, 270, 110, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_Register.setFont(font)
        self.btn_Register.setObjectName("btn_Register")

        self.retranslateUi(frm_Register)
        QtCore.QMetaObject.connectSlotsByName(frm_Register)

        # Event_Driven
        self.btn_Register.clicked.connect(self.register)

    def register(self):
        try:
            username = self.txt_username.text().lower()
            name = self.txt_Name.text().capitalize()
            password = self.txt_password.text()
            rePassword = self.txt_RePassword.text()
            # msg = QMessageBox()
            # msg.setWindowTitle("Register")
            # msg.setStyleSheet("QLabel{min-width: 50px;}")
            if self.isPasswordValid(password, rePassword) and self.isNameValid(name) and self.isUsernameValid(username):
                with pymongo.MongoClient(cloudDatabase) as conn:
                    db = conn.get_database('QT')
                    db.users.insert_one({'username': username,
                                         'password': password,
                                         'name': name,
                                         'last_access': datetime.now()
                                         })
                    # msg.setIcon(QMessageBox.Information)
                    # msg.setText("Success!")
                    # msg.exec_()
                    self.lbl_Result.setText("Success")
            else:
                # msg.setIcon(QMessageBox.Critical)
                # msg.setText("Error!")
                # msg.exec_()
                self.lbl_Result.setText("Error")
        except Exception as e:
            print(e)

    def isUsernameValid(self, username):
        if not username.isalnum():
            return False
        with pymongo.MongoClient(cloudDatabase) as conn:
            db = conn.get_database('QT')
            condition = {'username': {"$regex": f'^{username}$', "$options": "i"}}
            found = db.users.count_documents(condition)
            if found:
                return False
        return True

    def isNameValid(self, name):
        return all(x.isalpha or x == "" for x in name)

    def isPasswordValid(self, p1, p2):
        return p1 == p2

    def retranslateUi(self, frm_Register):
        _translate = QtCore.QCoreApplication.translate
        frm_Register.setWindowTitle(_translate("frm_Register", ".:: Register ::."))
        self.lbl_Username.setText(_translate("frm_Register", "Username"))
        self.lbl_Password.setText(_translate("frm_Register", "Password"))
        self.btn_Register.setText(_translate("frm_Register", "Register"))
        self.lbl_RePassword.setText(_translate("frm_Register", "Re-Password"))
        self.lbl_Name.setText(_translate("frm_Register", "Name"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    frm_Register = QtWidgets.QDialog()
    ui = Ui_frm_Register()
    ui.setupUi(frm_Register)
    frm_Register.show()
    sys.exit(app.exec_())
